### PR TITLE
Fix #1348: Error while loading lang.json

### LINKED ISSUE #1348: Error while loading lang.json
```
2023-06-06 16:50:26.267  WARN []  WARN 73680 --- [io-8080-exec-51] i.g.s.p.app.webflow.i18n.I18NService     : Error occurred while retrieving the language setting 

java.io.FileNotFoundException: URL [classpath:/static/resources/lang.json] cannot be resolved to absolute file path because it does not reside in the file system: classpath:/static/resources/lang.json
	at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:217) ~[spring-core-6.0.9.jar:6.0.9]
```

### PR DESCRIPTION
**Pull request by romanstrobl**

### CODE REVIEW

File: powerauth-webflow-i18n/src/main/java/io/getlime/security/powerauth/app/webflow/i18n/I18NService.java [hunk 1]
```diff
@@ -86,7 +86,8 @@ public AbstractMessageSource getMessageSource() {
     public String readLanguageSetting() {
         try {
             // language setting is possible only via extension and external resources
-            return new String(Files.readAllBytes(languageSettingSource.getFile().toPath()));
+            byte[] languageData = FileCopyUtils.copyToByteArray(languageSettingSource.getInputStream());
```
Comment (banterCZ) [inline powerauth-webflow-i18n/src/main/java/io/getlime/security/powerauth/app/webflow/i18n/I18NService.java:89]:
```suggestion
            final byte[] languageData = FileCopyUtils.copyToByteArray(languageSettingSource.getInputStream());
```

**Review by banterCZ — APPROVED** [review]
Looks good.
