### PR TITLE
Fix #1394: Error while loading lang.json

### LINKED ISSUE #1394: Error while loading lang.json
The language setting is not read correctly in the vanilla version. 

` Caused by: java.net.MalformedURLException: no protocol: lang.json
`

### PR DESCRIPTION
**Pull request by zcgandcomp**

### CODE REVIEW

File: powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/configuration/WebMvcConfiguration.java [hunk 1]
```diff
@@ -57,6 +57,9 @@ public class WebMvcConfiguration implements WebMvcConfigurer {
     @Autowired
     private WebFlowServerConfiguration configuration;
 
+    @Autowired
+    ResourceLoader resourceLoader;
```
Comment (banterCZ) [inline powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/configuration/WebMvcConfiguration.java:61]:
```suggestion
    private ResourceLoader resourceLoader;
```

**Review by banterCZ — APPROVED** [review]
Looks good.
