### PR TITLE
Fix #981: Update soft attempt counter reset logic

### LINKED ISSUE #981: Update soft failed attempt counter reset logic
Currently the soft failed attempt counter reset logic in endpoint `/credential/counter/reset-all` is following:
- when the credential status is `BLOCKED_TEMPORARY`, the soft failed attempt counter is reset and status is set to `ACTIVE`

We should update the logic:
- when the credential status is `BLOCKED_TEMPORARY`, the soft failed attempt counter is reset and status is set to `ACTIVE`
- when the credential status is `ACTIVE`, the soft failed attempt counter is reset

This will allow all clients to start with clean slate in the beginning of every day.

### PR DESCRIPTION
**Pull request by romanstrobl**
Updated logic for reseting soft counters based on more detailed requirements.

### CODE REVIEW

File: powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/CredentialCounterService.java [hunk 1]
```diff
@@ -137,14 +137,26 @@ public void updateCredentialCounter(CredentialEntity credential, AuthenticationR
     @Transactional
     public ResetCountersResponse resetCounters(ResetCountersRequest request) {
```
Comment (petrdvorak) [inline powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/CredentialCounterService.java:138]: The request should contain info about the type of reset. Otherwise, the side-effect can be unexpected. For example:

```json
{
    "active": true,
    "blocked": true
}
```

File: powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/CredentialCounterService.java [hunk 2]
```diff
@@ -137,14 +137,26 @@ public void updateCredentialCounter(CredentialEntity credential, AuthenticationR
...
+        // Reset soft counters for credentials with status BLOCKED_TEMPORARY and set status to ACTIVE
         for (CredentialEntity credential: blockedCredentials) {
             credential.setStatus(CredentialStatus.ACTIVE);
             credential.setFailedAttemptCounterSoft(0);
             credential.setTimestampBlocked(null);
+            resetCounter++;
         }
         credentialRepository.saveAll(blockedCredentials);
+        // Reset soft counters for credentials with status ACTIVE with non-zero soft counter
+        final List<CredentialEntity> activeCredentials = credentialRepository.findAllByStatus(CredentialStatus.ACTIVE);
```
Comment (petrdvorak) [inline powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/CredentialCounterService.java:150]: This is a horrible query that will basically return all customers at once. We should:

- scope it only to those credentials that have non-zero counter
- use paging / limit results (unless Hibernate does some serious magic)

File: powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/CredentialCounterService.java [hunk 3]
```diff
@@ -137,14 +137,26 @@ public void updateCredentialCounter(CredentialEntity credential, AuthenticationR
     @Transactional
     public ResetCountersResponse resetCounters(ResetCountersRequest request) {
         final List<CredentialEntity> blockedCredentials = credentialRepository.findAllByStatus(CredentialStatus.BLOCKED_TEMPORARY);
```
Comment (petrdvorak) [inline powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/CredentialCounterService.java:139]: Consider paging.

**Review by petrdvorak — APPROVED** [review]
The change is less terrible than I expected, but we should have a look at performance and granularity of configuration.

**Review by petrdvorak — CHANGES_REQUESTED** [review]
Apologies - the approve was unintended.

File: powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/CredentialCounterService.java (hunk 2 above)
Comment (romanstrobl) [reply powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/CredentialCounterService.java:150]: I think we can avoid performance issues by executing SQL updates directly. In this case the logic is quite basic, so we don't need to query the data. Thanks for pointing it out.

File: powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/CredentialCounterService.java (hunk 1 above)
Comment (romanstrobl) [reply powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/CredentialCounterService.java:138]: I prefer an enumeration parameter because I think there are two use cases here, not four (from the booleans in example): `RESET_BLOCKED`, `RESET_ACTIVE_AND_BLOCKED`.

File: powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/CredentialCounterService.java (hunk 3 above)
Comment (romanstrobl) [reply powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/CredentialCounterService.java:139]: I will switch to SQL update to avoid performance issues.

**Comment by romanstrobl** [comment]
All performance issues should be gone now.

**Review by petrdvorak — APPROVED** [review]
Looks OK
