### PR TITLE
Fix #884: Backport non-problematic fixes to 0.24.x

### LINKED ISSUE #884: Backport non-problematic fixes to 0.24.x
- Add WebLogic descriptor.
- Fix documentation.
- Fix default DDL scripts.

### PR DESCRIPTION
**Pull request by petrdvorak**

### CODE REVIEW

File: docs/sql/oracle/create_schema.sql [hunk 1]
```diff
@@ -257,7 +257,7 @@ CREATE TABLE tpp_user_consent (
     user_id             VARCHAR(256) NOT NULL,                      -- User ID.
     client_id           VARCHAR(256) NOT NULL,                      -- OAuth 2.0 client ID.
     consent_id          VARCHAR(64) NOT NULL,                       -- Consent ID.
-    external_id         VARCHAR(256) NOT NULL,                      -- External ID associated with the consent approval, usually the operation ID.
+    external_id         VARCHAR(256),                      -- External ID associated with the consent approval, usually the operation ID.
```
Comment (romanstrobl) [inline docs/sql/oracle/create_schema.sql:260]: Comment is not properly formatted.

File: docs/sql/oracle/create_schema.sql [hunk 2]
```diff
@@ -270,7 +270,7 @@ CREATE TABLE tpp_user_consent_history (
     client_id           VARCHAR(256) NOT NULL,                      -- Client ID.
     consent_id          VARCHAR(64) NOT NULL,                       -- Consent ID.
     consent_change      VARCHAR(16) NOT NULL,                       -- Type of the consent change: APPROVE, PROLONG, REJECT
-    external_id         VARCHAR(256) NOT NULL,                      -- External ID that was responsible for this specific consent change, usually the operation ID.
+    external_id         VARCHAR(256),                      -- External ID that was responsible for this specific consent change, usually the operation ID.
```
Comment (romanstrobl) [inline docs/sql/oracle/create_schema.sql:273]: dtto

**Review by romanstrobl — APPROVED** [review]
Looks good, I found two very minor formatting issues.
