### PR TITLE
Fix #454: Fix issues found by coverity scan

### LINKED ISSUE #454: Fix issues found by coverity scan
20 issues were found by coverity scan, we should investigate them and fix them if possible.

### PR DESCRIPTION
**Pull request by romanstrobl**

### CODE REVIEW

File: powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/service/WebSocketMessageService.java [hunk 1]
```diff
@@ -95,13 +95,23 @@ public void sendRegistrationMessage(String webSocketId, String sessionId) {
...
+    }
+
     /**
      * Relate a new web socket identifier to the session with given ID.
      *
      * @param webSocketId Web Socket ID.
      * @param sessionId Session ID.
      */
-    public void putWebSocketSession(String webSocketId, String sessionId) {
+    public synchronized void putWebSocketSession(String webSocketId, String sessionId) {
```
Comment (petrdvorak) [inline powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/service/WebSocketMessageService.java]: Probably better to use a synchonized `Map`...

File: powerauth-webflow-authentication-sms/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/sms/controller/SMSAuthorizationController.java [hunk 2]
```diff
@@ -71,7 +71,10 @@ protected String authenticate(SMSAuthorizationRequest request) throws AuthStepEx
         final GetOperationDetailResponse operation = getOperation();
         Logger.getLogger(this.getClass().getName()).log(Level.INFO, "Step authentication started, operation ID: {0}, authentication method: {1}", new String[] {operation.getOperationId(), getAuthMethodName().toString()});
         checkOperationExpiration(operation);
-        final Object messageId = httpSession.getAttribute(MESSAGE_ID);
+        final Object messageId;
+        synchronized (httpSession.getServletContext()) {
```
Comment (petrdvorak) [inline powerauth-webflow-authentication-sms/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/sms/controller/SMSAuthorizationController.java]: Can this be written in some better way? I am not sure if it is a good idea to use `synchronized` keyword in the server-side code... if there is a better way, let's improve it in all instances...

**Comment by petrdvorak** [comment]
... discussed offline, the code is correct.
