### PR TITLE
Fix #1980: Coverity: Unlogged security exception

### LINKED ISSUE #1980: Coverity: Unlogged security exception
### Task specification

_No response_

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

File: powerauth-nextstep/src/main/java/com/wultra/security/powerauth/app/nextstep/service/EndToEndEncryptionService.java [hunk 1]
```diff
@@ -103,6 +101,7 @@ public String encryptCredential(String credentialValue, CredentialDefinitionEnti
             final String ivBase64 = Base64.getEncoder().encodeToString(ivBytes);
             return ivBase64 + ":" + encryptedCredentialBase64;
         } catch (CryptoProviderException | InvalidKeyException | GenericCryptoException ex) {
+            logger.debug("Failed to encrypt credential value", ex);
```
Comment (banterCZ) [inline powerauth-nextstep/src/main/java/com/wultra/security/powerauth/app/nextstep/service/EndToEndEncryptionService.java:104]: It is logged in the exception handler, but to satisfy Coverity scan.

**Review by michal-rozehnal-w — APPROVED** [review]
